name: Examples
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Dev package
        run: julia -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
      - name: Run examples
        shell: julia --project=examples --color=yes {0}
        run: |
          using Pkg
          Pkg.instantiate()
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.add(PackageSpec(path=joinpath(pwd(), "../../Hypatia"))
          Pkg.status()
          include("examples/runexamplestests.jl")
          exit(1)